In [1]:
import pandas as pd

df = pd.read_csv("Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [2]:
df.tail()

      Id  SepalLengthCm  ...  PetalWidthCm         Species
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[5 rows x 6 columns]

In [3]:
print(df.shape)
print(df.dtypes)
df.info()

(150, 6)
Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [4]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
print(df.isnull().sum())
print("Duplicate rows:", df.duplicated().sum())
print(df["Species"].unique())

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64
Duplicate rows: 0
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

In [6]:
df.loc[df["Species"] == "Iris-setosa", ["SepalLengthCm", "SepalWidthCm", "Species"]].head()

   SepalLengthCm  SepalWidthCm      Species
0            5.1           3.5  Iris-setosa
1            4.9           3.0  Iris-setosa
2            4.7           3.2  Iris-setosa
3            4.6           3.1  Iris-setosa
4            5.0           3.6  Iris-setosa

In [7]:
data = df.copy()
data.loc[0, "SepalLengthCm"] = None
data.loc[1, "Species"] = None
data = pd.concat([data, data.iloc[[2]]], ignore_index=True)
print(data.isnull().sum())
print("Duplicates:", data.duplicated().sum())

Id               0
SepalLengthCm    1
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          1
dtype: int64
Duplicates: 1

In [8]:
data["SepalLengthCm"] = data["SepalLengthCm"].fillna(data["SepalLengthCm"].mean())
data["Species"] = data["Species"].fillna(data["Species"].mode()[0])
data = data.drop_duplicates()
print(data.isnull().sum())
print("Duplicates:", data.duplicated().sum())

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64
Duplicates: 0

In [9]:
data = data.drop("Id", axis=1)
data.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0       5.840667           3.5            1.4           0.2  Iris-setosa
1       4.900000           3.0            1.4           0.2  Iris-setosa
2       4.700000           3.2            1.3           0.2  Iris-setosa
3       4.600000           3.1            1.5           0.2  Iris-setosa
4       5.000000           3.6            1.4           0.2  Iris-setosa

In [10]:
data.loc[data["SepalLengthCm"] > 6].head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
50            7.0           3.2            4.7           1.4  Iris-versicolor
51            6.4           3.2            4.5           1.5  Iris-versicolor
52            6.9           3.1            4.9           1.5  Iris-versicolor
54            6.5           2.8            4.6           1.5  Iris-versicolor
56            6.3           3.3            4.7           1.6  Iris-versicolor

In [11]:
data.groupby("Species")["SepalLengthCm"].mean()

Species
Iris-setosa        5.020813
Iris-versicolor    5.936000
Iris-virginica     6.588000
Name: SepalLengthCm, dtype: float64

In [12]:
data.sort_values("SepalLengthCm", ascending=False).head()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
131            7.9           3.8            6.4           2.0  Iris-virginica
122            7.7           2.8            6.7           2.0  Iris-virginica
118            7.7           2.6            6.9           2.3  Iris-virginica
117            7.7           3.8            6.7           2.2  Iris-virginica
135            7.7           3.0            6.1           2.3  Iris-virginica